var nombreDeSuperHeroe= 'Batman';
var nombre= 'Bruce Wayne';
var maneja= 'si';
var vida= 30;
var trabajo= undefined;
var tiempoLibre= null;
console.log('nombreDeSuperHeroe'+' '+nombreDeSuperHeroe);
console.log('nombre'+' '+nombre);
console.log('maneja'+' '+maneja);
console.log('vida'+' '+vida);
console.log('trabajo'+' '+trabajo);
console.log('tiempoLibre'+' '+tiempoLibre);
console.log(typeof nombreDeSuperHeroe);
console.log(typeof nombre);
console.log(typeof maneja);
console.log(typeof vida);
console.log(typeof trabajo);
console.log(typeof tiempoLibre);