var numero, factor;
numero= 9;
factor= 1;
console.log(numero+'X'+factor+'='+(numero*factor));
factor++;
console.log(numero+'X'+factor+'='+(numero*factor));
factor++;
console.log(numero+'X'+factor+'='+(numero*factor));
factor++;
console.log(numero+'X'+factor+'='+(numero*factor));
factor++;
console.log(numero+'X'+factor+'='+(numero*factor));
factor++;
console.log(numero+'X'+factor+'='+(numero*factor));
factor++;
console.log(numero+'X'+factor+'='+(numero*factor));
factor++;
console.log(numero+'X'+factor+'='+(numero*factor));
factor++;
console.log(numero+'X'+factor+'='+(numero*factor));
factor++;
console.log(numero+'X'+factor+'='+(numero*factor));
