var cantidadDeUsuarios = 100;
cantidadDeUsuarios += 5;
console.log (' Cantidad de usuarios: ', cantidadDeUsuarios);
cantidadDeUsuarios -= 3;
console.log (' Cantidad de usuarios: ', cantidadDeUsuarios);
cantidadDeUsuarios *= 3;
console.log (' Cantidad de usuarios: ', cantidadDeUsuarios);
cantidadDeUsuarios /= 2;
console.log ('Total de usuarios femeninos: ', cantidadDeUsuarios);
console.log ('Total de usuarios masculinos: ', cantidadDeUsuarios);